In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import tensorflow as tf

In [2]:
dataf = pd.read_csv('./datacarreras.csv', delimiter=',')
dataf.head()

,fecha,numero_carrera,distancia_pista,grupo,nombre_caballo,tiempo,ult_div,penult_div,posicion,cuerpos_ult,cuerpos_penult,distancia_c,lote,jinete_act,jinete_gana,jinete_rep_mon,trainer_act,trainer_gana,resultado
0,08-11-2020,1,1800,2,ironhide,113.0,2100,2300,2,4.25,8.50,2,2,122,16,3,49,5,6
1,08-11-2020,1,1800,2,el ferretero,114.2,10000,10000,7,11.25,13.00,1,3,69,1,1,50,0,3
2,08-11-2020,1,1800,2,matheew star,115.0,350,350,5,6.50,4.25,2,3,43,5,3,93,8,4
3,08-11-2020,1,1800,2,power indy,113.3,450,600,3,6.50,5.50,3,3,99,14,1,146,19,1
4,08-11-2020,1,1800,2,gran giacomo,115.2,540,540,1,0.00,0.50,2,1,92,23,1,31,6,8

In [3]:
dataf["fecha"] = (dataf["fecha"].apply(lambda x: x.replace("-", "").strip()).astype(np.int64))
dataf.drop(labels='nombre_caballo', axis=1, inplace=True)
unique_fechas = dataf["fecha"].unique()
dataf = dataf.groupby(["fecha", "numero_carrera"])
unique_fechas

array([ 8112020, 15112020, 12122020, 13122020, 19122020, 20122020,
       10012021, 17012021, 30012021,  7022021, 14022021, 21022021,
       28022021,  7032021, 14032021, 21032021, 28032021,  4042021,
       11042021, 18042021], dtype=int64)

In [4]:
dataf.get_group((8112020, 1))

,fecha,numero_carrera,distancia_pista,grupo,tiempo,ult_div,penult_div,posicion,cuerpos_ult,cuerpos_penult,distancia_c,lote,jinete_act,jinete_gana,jinete_rep_mon,trainer_act,trainer_gana,resultado
0,8112020,1,1800,2,113.0,2100,2300,2,4.25,8.50,2,2,122,16,3,49,5,6
1,8112020,1,1800,2,114.2,10000,10000,7,11.25,13.00,1,3,69,1,1,50,0,3
2,8112020,1,1800,2,115.0,350,350,5,6.50,4.25,2,3,43,5,3,93,8,4
3,8112020,1,1800,2,113.3,450,600,3,6.50,5.50,3,3,99,14,1,146,19,1
4,8112020,1,1800,2,115.2,540,540,1,0.00,0.50,2,1,92,23,1,31,6,8
5,8112020,1,1800,2,114.0,200,220,4,9.00,5.00,3,3,4,0,1,146,19,2
6,8112020,1,1800,2,119.2,6300,10000,11,11.00,14.75,3,2,118,13,3,69,6,5
7,8112020,1,1800,2,117.5,10000,10000,11,15.25,19.75,1,3,9,1,1,50,0,9
8,8112020,1,1800,2,114.2,10000,10000,5,6.25,11.25,0,3,88,6,3,31,2,7

In [5]:
data_carreras = []

def getRaces(dataframe, num_races):
    for i in np.array(num_races):
        for r in range(1, 13):
            try:
                df = dataframe.get_group((i, r))
                df = tf.convert_to_tensor(df, dtype=tf.float64)
                data_carreras.append(df)
            except KeyError:
                print(f"No data found for ID: {r}, Race num: {i}")

In [6]:
getRaces(dataf, unique_fechas[:2])
data_carreras[:2]

No data found for ID: 2, Race num: 8112020
No data found for ID: 11, Race num: 15112020
No data found for ID: 12, Race num: 15112020

[<tf.Tensor: shape=(9, 18), dtype=float64, numpy=
 array([[8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.13000e+02,
         2.10000e+03, 2.30000e+03, 2.00000e+00, 4.25000e+00, 8.50000e+00,
         2.00000e+00, 2.00000e+00, 1.22000e+02, 1.60000e+01, 3.00000e+00,
         4.90000e+01, 5.00000e+00, 6.00000e+00],
        [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.14200e+02,
         1.00000e+04, 1.00000e+04, 7.00000e+00, 1.12500e+01, 1.30000e+01,
         1.00000e+00, 3.00000e+00, 6.90000e+01, 1.00000e+00, 1.00000e+00,
         5.00000e+01, 0.00000e+00, 3.00000e+00],
        [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.15000e+02,
         3.50000e+02, 3.50000e+02, 5.00000e+00, 6.50000e+00, 4.25000e+00,
         2.00000e+00, 3.00000e+00, 4.30000e+01, 5.00000e+00, 3.00000e+00,
         9.30000e+01, 8.00000e+00, 4.00000e+00],
        [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.13300e+02,
         4.50000e+02, 6.00000e+02, 3.00000e+00, 6.50000e+00, 5.50000e+00,
         3.00000e+00, 3.00000e+00, 9.90000e+01, 1.40000e+01, 1.00000e+00,
         1.46000e+02, 1.90000e+01, 1.00000e+00],
        [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.15200e+02,
         5.40000e+02, 5.40000e+02, 1.00000e+00, 0.00000e+00, 5.00000e-01,
         2.00000e+00, 1.00000e+00, 9.20000e+01, 2.30000e+01, 1.00000e+00,
         3.10000e+01, 6.00000e+00, 8.00000e+00],
        [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.14000e+02,
         2.00000e+02, 2.20000e+02, 4.00000e+00, 9.00000e+00, 5.00000e+00,
         3.00000e+00, 3.00000e+00, 4.00000e+00, 0.00000e+00, 1.00000e+00,
         1.46000e+02, 1.90000e+01, 2.00000e+00],
        [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.19200e+02,
         6.30000e+03, 1.00000e+04, 1.10000e+01, 1.10000e+01, 1.47500e+01,
         3.00000e+00, 2.00000e+00, 1.18000e+02, 1.30000e+01, 3.00000e+00,
         6.90000e+01, 6.00000e+00, 5.00000e+00],
        [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.17500e+02,
         1.00000e+04, 1.00000e+04, 1.10000e+01, 1.52500e+01, 1.97500e+01,
         1.00000e+00, 3.00000e+00, 9.00000e+00, 1.00000e+00, 1.00000e+00,
         5.00000e+01, 0.00000e+00, 9.00000e+00],
        [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.14200e+02,
         1.00000e+04, 1.00000e+04, 5.00000e+00, 6.25000e+00, 1.12500e+01,
         0.00000e+00, 3.00000e+00, 8.80000e+01, 6.00000e+00, 3.00000e+00,
         3.10000e+01, 2.00000e+00, 7.00000e+00]])>,
 <tf.Tensor: shape=(8, 18), dtype=float64, numpy=
 array([[8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.13000e+01,
         8.00000e+02, 3.00000e+02, 7.00000e+00, 1.20000e+01, 0.00000e+00,
         3.00000e+00, 1.00000e+00, 1.40000e+02, 2.70000e+01, 1.00000e+00,
         7.40000e+01, 5.00000e+00, 5.00000e+00],
        [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.04000e+01,
         1.50000e+03, 1.80000e+03, 4.00000e+00, 6.75000e+00, 4.50000e+00,
         1.00000e+00, 3.00000e+00, 9.90000e+01, 1.40000e+01, 3.00000e+00,
         7.40000e+01, 5.00000e+00, 6.00000e+00],
        [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 7.92000e+01,
         9.00000e+02, 9.00000e+02, 7.00000e+00, 1.45000e+01, 7.00000e+00,
         3.00000e+00, 4.00000e+00, 3.10000e+01, 1.00000e+00, 1.00000e+00,
         1.17000e+02, 5.00000e+00, 1.00000e+00],
        [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.00000e+01,
         1.00000e+03, 6.00000e+02, 3.00000e+00, 3.25000e+00, 1.45000e+01,
         2.00000e+00, 3.00000e+00, 9.80000e+01, 1.80000e+01, 3.00000e+00,
         8.70000e+01, 1.30000e+01, 4.00000e+00],
        [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 7.83000e+01,
         1.26000e+03, 1.26000e+03, 1.00000e+00, 0.00000e+00, 3.25000e+00,
         3.00000e+00, 1.00000e+00, 7.60000e+01, 1.00000e+01, 1.00000e+00,
         9.70000e+01, 1.80000e+01, 2.00000e+00],
        [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 7.94000e+01,
         1.40000e+03, 1.40000e+03, 6.00000e+00, 7.00000e+00, 7.00000e+00,
         3.00000e+00, 1.00000e+00, 7.60000e+01, 5.00000e+00, 1.00000e+00,
         1.59000e+02, 2.40000e+01, 7.00000e+00],
        [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.04000e+01,
         1.80000e+03, 1.80000e+03, 3.00000e+00, 1.00000e+00, 1.00000e+00,
         3.00000e+00, 3.00000e+00, 1.47000e+02, 3.80000e+01, 1.00000e+00,
         2.36000e+02, 3.40000e+01, 3.00000e+00],
        [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.03000e+01,
         9.90000e+02, 9.90000e+02, 1.00000e+00, 0.00000e+00, 0.00000e+00,
         2.00000e+00, 1.00000e+00, 1.00000e+02, 1.30000e+01, 1.00000e+00,
         2.20000e+01, 4.00000e+00, 8.00000e+00]])>]

In [7]:
data_carreras = np.array(data_carreras, dtype=object)
data_carreras[:2]

array([<tf.Tensor: shape=(9, 18), dtype=float64, numpy=
       array([[8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.13000e+02,
               2.10000e+03, 2.30000e+03, 2.00000e+00, 4.25000e+00, 8.50000e+00,
               2.00000e+00, 2.00000e+00, 1.22000e+02, 1.60000e+01, 3.00000e+00,
               4.90000e+01, 5.00000e+00, 6.00000e+00],
              [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.14200e+02,
               1.00000e+04, 1.00000e+04, 7.00000e+00, 1.12500e+01, 1.30000e+01,
               1.00000e+00, 3.00000e+00, 6.90000e+01, 1.00000e+00, 1.00000e+00,
               5.00000e+01, 0.00000e+00, 3.00000e+00],
              [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.15000e+02,
               3.50000e+02, 3.50000e+02, 5.00000e+00, 6.50000e+00, 4.25000e+00,
               2.00000e+00, 3.00000e+00, 4.30000e+01, 5.00000e+00, 3.00000e+00,
               9.30000e+01, 8.00000e+00, 4.00000e+00],
              [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.13300e+02,
               4.50000e+02, 6.00000e+02, 3.00000e+00, 6.50000e+00, 5.50000e+00,
               3.00000e+00, 3.00000e+00, 9.90000e+01, 1.40000e+01, 1.00000e+00,
               1.46000e+02, 1.90000e+01, 1.00000e+00],
              [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.15200e+02,
               5.40000e+02, 5.40000e+02, 1.00000e+00, 0.00000e+00, 5.00000e-01,
               2.00000e+00, 1.00000e+00, 9.20000e+01, 2.30000e+01, 1.00000e+00,
               3.10000e+01, 6.00000e+00, 8.00000e+00],
              [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.14000e+02,
               2.00000e+02, 2.20000e+02, 4.00000e+00, 9.00000e+00, 5.00000e+00,
               3.00000e+00, 3.00000e+00, 4.00000e+00, 0.00000e+00, 1.00000e+00,
               1.46000e+02, 1.90000e+01, 2.00000e+00],
              [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.19200e+02,
               6.30000e+03, 1.00000e+04, 1.10000e+01, 1.10000e+01, 1.47500e+01,
               3.00000e+00, 2.00000e+00, 1.18000e+02, 1.30000e+01, 3.00000e+00,
               6.90000e+01, 6.00000e+00, 5.00000e+00],
              [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.17500e+02,
               1.00000e+04, 1.00000e+04, 1.10000e+01, 1.52500e+01, 1.97500e+01,
               1.00000e+00, 3.00000e+00, 9.00000e+00, 1.00000e+00, 1.00000e+00,
               5.00000e+01, 0.00000e+00, 9.00000e+00],
              [8.11202e+06, 1.00000e+00, 1.80000e+03, 2.00000e+00, 1.14200e+02,
               1.00000e+04, 1.00000e+04, 5.00000e+00, 6.25000e+00, 1.12500e+01,
               0.00000e+00, 3.00000e+00, 8.80000e+01, 6.00000e+00, 3.00000e+00,
               3.10000e+01, 2.00000e+00, 7.00000e+00]])>                       ,
       <tf.Tensor: shape=(8, 18), dtype=float64, numpy=
       array([[8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.13000e+01,
               8.00000e+02, 3.00000e+02, 7.00000e+00, 1.20000e+01, 0.00000e+00,
               3.00000e+00, 1.00000e+00, 1.40000e+02, 2.70000e+01, 1.00000e+00,
               7.40000e+01, 5.00000e+00, 5.00000e+00],
              [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.04000e+01,
               1.50000e+03, 1.80000e+03, 4.00000e+00, 6.75000e+00, 4.50000e+00,
               1.00000e+00, 3.00000e+00, 9.90000e+01, 1.40000e+01, 3.00000e+00,
               7.40000e+01, 5.00000e+00, 6.00000e+00],
              [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 7.92000e+01,
               9.00000e+02, 9.00000e+02, 7.00000e+00, 1.45000e+01, 7.00000e+00,
               3.00000e+00, 4.00000e+00, 3.10000e+01, 1.00000e+00, 1.00000e+00,
               1.17000e+02, 5.00000e+00, 1.00000e+00],
              [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.00000e+01,
               1.00000e+03, 6.00000e+02, 3.00000e+00, 3.25000e+00, 1.45000e+01,
               2.00000e+00, 3.00000e+00, 9.80000e+01, 1.80000e+01, 3.00000e+00,
               8.70000e+01, 1.30000e+01, 4.00000e+00],
              [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 7.83000e+01,
               1.26000e+03, 1.26000e+03, 1.00000e+00, 0.00000e+00, 3.25000e+00,
               3.00000e+00, 1.00000e+00, 7.60000e+01, 1.00000e+01, 1.00000e+00,
               9.70000e+01, 1.80000e+01, 2.00000e+00],
              [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 7.94000e+01,
               1.40000e+03, 1.40000e+03, 6.00000e+00, 7.00000e+00, 7.00000e+00,
               3.00000e+00, 1.00000e+00, 7.60000e+01, 5.00000e+00, 1.00000e+00,
               1.59000e+02, 2.40000e+01, 7.00000e+00],
              [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.04000e+01,
               1.80000e+03, 1.80000e+03, 3.00000e+00, 1.00000e+00, 1.00000e+00,
               3.00000e+00, 3.00000e+00, 1.47000e+02, 3.80000e+01, 1.00000e+00,
               2.36000e+02, 3.40000e+01, 3.00000e+00],
              [8.11202e+06, 3.00000e+00, 1.30000e+03, 2.00000e+00, 8.03000e+01,
               9.90000e+02, 9.90000e+02, 1.00000e+00, 0.00000e+00, 0.00000e+00,
               2.00000e+00, 1.00000e+00, 1.00000e+02, 1.30000e+01, 1.00000e+00,
               2.20000e+01, 4.00000e+00, 8.00000e+00]])>                       ],
      dtype=object)